# Generated by Django 5.0.7 on 2026-09-21 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento (C.C. / N.I.T.)')),
                ('rol', models.CharField(choices=[('Paciente', 'Paciente'), ('Profesional', 'Profesional'), ('Personal Administrativo', 'Personal Administrativo'), ('Administrador del Sistema', 'Administrador del Sistema'), ('Gerente / Dueño', 'Gerente / Dueño')], default='Paciente', max_length=30, verbose_name='Rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
